image: docker:latest
services:
  - docker:dind

cache:
  key: "$CI_PIPELINE_ID"
  untracked: true

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - release
  - test
  - deploy

before_script:
  - docker version
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:wasm:
  stage: build
  script:
    - docker build -t registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID -f docker/Dockerfile_wasm .
    - docker push registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID

build:wasm:
  stage: build
  script:
    - docker build -t registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID -f docker/Dockerfile_wasm .
    - docker push registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID

build:devserver:
  stage: build
  script:
    - docker build -t registry.gitlab.com/mattmatters/opencv-wasm/devserver:$CI_PIPELINE_ID -f docker/Dockerfile_devserver .
    - docker push registry.gitlab.com/mattmatters/opencv-wasm/devserver:$CI_PIPELINE_ID

build:e2e:
  stage: build
  script:
    - docker build -t registry.gitlab.com/mattmatters/opencv-wasm/e2e:$CI_PIPELINE_ID -f docker/Dockerfile_e2e .
    - docker push registry.gitlab.com/mattmatters/opencv-wasm/e2e:$CI_PIPELINE_ID

# Prepare everything for release
release:wasm:
  stage: release
  artifacts:
    paths:
      - dist/
  script:
    - docker pull registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID
    - mkdir dist
    - docker run -v "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/dist:/usr/src/app/dist registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID

release:js:
  image: python:latest
  before_script:
    - echo "overwrite before_script"
  stage: release
  artifacts:
    paths:
      - dist/
  script:
    - bash ./scripts/build_static.sh

test:e2e:
  stage: test
  dependencies:
    - release:wasm
    - release:js
  script:
    - docker pull registry.gitlab.com/mattmatters/opencv-wasm/devserver:$CI_PIPELINE_ID
    - docker pull registry.gitlab.com/mattmatters/opencv-wasm/e2e:$CI_PIPELINE_ID
    - docker run -v $(pwd)/dist:/usr/share/nginx/html --env BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY --env BROWSERSTACK_USER=$BROWSERSTACK_USER -p 80:80 -d registry.gitlab.com/mattmatters/opencv-wasm/devserver:$CI_PIPELINE_ID
    - docker run registry.gitlab.com/mattmatters/opencv-wasm/e2e:$CI_PIPELINE_ID
    - docker stop registry.gitlab.com/mattmatters/opencv-wasm/devserver:$CI_PIPELINE_ID

deploy:
  image: python:latest
  stage: deploy
  dependencies:
    - release:wasm
    - release:js
  variables:
    BUCKET: "s3://opencvwasm"
  before_script:
    - pip install awscli
  script:
    - bash scripts/deploy.sh
  only:
    - master
