image: docker:latest
services:
  - docker:dind

cache:
  key: "$CI_PIPELINE_ID"
  untracked: true

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - release
  - deploy

before_script:
  - docker version
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:wasm:
  stage: build
  script:
    - docker build -t registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID -f docker/Dockerfile_wasm .
    - docker push registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID

# Prepare everything for release
release:wasm:
  stage: release
  artifacts:
    paths:
      - dist/
  script:
    - docker pull registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID
    - mkdir dist
    - docker run -v "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/dist:/usr/src/app/dist registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID
  only:
    - master

release:js:
  stage: release
  artifacts:
    paths:
      - dist/
  script:
    - bash ./scripts/build_static.sh
  only:
    - master

deploy:
  image: python:latest
  stage: deploy
  dependencies:
    - release:wasm
    - release:js
  variables:
    BUCKET: "s3://opencvwasm"
  before_script:
    - pip install awscli
  script:
    - bash deploy.sh
  only:
    - master
