image: docker:latest
services:
  - docker:dind

cache:
  key: "$CI_PIPELINE_ID"
  untracked: true

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - release
  - deploy

before_script:
  - docker version
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build_wasm:
  stage: build
  script:
    - docker build -t registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID .
    - docker push registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID

# Prepare everything for release
release_wasm:
  stage: release
  script:
    - docker pull registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID
    - docker run -v "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/web:/usr/src/app/web registry.gitlab.com/mattmatters/opencv-wasm/wasm:$CI_PIPELINE_ID
    - ls
    - echo $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
    - ls ./web
  only:
    - master

deploy:
  image: python:latest
  stage: deploy
  variables:
    BUCKET: "s3://opencvwasm/"
  before_script:
    - pip install awscli
  script:
    - aws s3 cp ./web $BUCKET --recursive
  only:
    - master
