version: "3.1"
services:
  wasm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - fun:/usr/src/app/web
  devserver:
    depends_on:
      - wasm
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: server
    volumes:
      - fun:/usr/share/nginx/html
volumes:
  fun:
