version: "3.1"
services:
  devserver:
    build:
      context: .
      dockerfile: server
    ports:
      - "8080:80"
  wasm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: /bin/bash -c "source /usr/emsdk/emsdk_env.sh && emcmake cmake && emmake make"
