version: "3.1"
services:
  devserver:
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: server
    volumes:
      - fun:/usr/share/nginx/html
  wasm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - fun:/usr/src/app/web
      - ./web:/usr/src/app/web
volumes:
  fun:
