FROM trzeci/emscripten:latest

# For some reason ubuntu is forcing this to be an interactive thing on update

# Update distro and install essentials
RUN apt-get -y install bzip2 \
    wget \
    bzip2 \
    unzip

RUN cd /usr

# Get latest opencv
RUN wget https://github.com/opencv/opencv/archive/3.4.0.zip && \
    unzip 3.4.0.zip && \
    cd opencv-3.4.0 && \
    python ./platforms/js/build_js.py build_wasm --build_wasm

# Install dlib
RUN wget http://dlib.net/files/dlib-19.6.tar.bz2 && \
    tar xvf dlib-19.6.tar.bz2 && \
    cd dlib-19.6/ && \
    mkdir build && \
    cd build && \
    cmake .. && \
    cmake --build . --config Release && \
    make install && \
    ldconfig && \
    cd ..

# Update to latest cmake, current one has a nasty bug that affects the project
# RUN apt-get purge -y cmake && \
#     mkdir temp-c && \
#     cd temp-c && \
#     wget https://cmake.org/files/v3.10/cmake-3.10.0.tar.gz && \
#     tar -xzvf cmake-3.10.0.tar.gz && \
#     cd cmake-3.10.0 && \
#     ./bootstrap && \
#     make -j4 && \
#     make install

WORKDIR /usr/src/app

RUN cd /usr/src/app

RUN mkdir dep && cd dep

RUN wget http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2 && \
    bzip2 -d -v shape_predictor_68_face_landmarks.dat.bz2 && \
    wget https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_alt2.xml

RUN cd /usr/src/app

COPY ./cpp .
COPY ./scripts/build.sh .

RUN ./build.sh

CMD ./build.sh
